# Site/SEO settings
email: dergigi@pm.me
baseurl: ""
permalink: /:year/:month/:day/:title/
google_analytics:

name: Gigi
title: Einundzwanzig - Der Bitcoin Podcast
description: >
  Thoughts about Bitcoin and other things.
url: https://dergigi.com
twitter_username: dergigi
default_img: /assets/images/einundzwanzig-square.png
social:
  - name: podcast
    url: https://anchor.fm/einundzwanzig

hosts:
  - name: Markus
    url: https://twitter.com/allgaeucrypto
    image: /assets/images/markus.png
  - name: Gigi
    url: https://twitter.com/dergigi
    image: /assets/images/gigi.png
  - name: Fabio
    url: https://twitter.com/fabthefoxx
    image: /assets/images/fabio.jpg
  - name: Daniel
    url: https://twitter.com/danielwingen
    image: /assets/images/daniel.jpg

# Build settings
markdown: kramdown
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-redirect-from
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]
exclude:
  - env
  - scripts
  - node_modules
  - .DS_Store
  - barber.jpg
  - Gemfile
  - Gemfile.lock
  - gulpfile.js
  - package.json
  - README.md
